[mypy]
ignore_missing_imports = True
warn_unused_configs = True
show_error_codes = True
no_implicit_optional = True
warn_redundant_casts = True
strict_equality = True
# Type-checking is targeted; tracking inference module fixes in v0.3 issue.
disable_error_code = misc, union-attr, no-redef, assignment

[mypy-networkx.*]
ignore_missing_imports = True

[mypy-opt_einsum.*]
ignore_missing_imports = True

[mypy-pgmpy.*]
ignore_missing_imports = True

[mypy-pyro.*]
ignore_missing_imports = True

[mypy-gpytorch.*]
ignore_missing_imports = True

[mypy-zuko.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-seaborn.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-filelock.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True
