"""v0.6c-C-3 — table writers (CSV / markdown / LaTeX / parquet).

Consumes the ``aggregate(...)`` output from ``_aggregate.py`` and
writes 4 file formats per crash-test run.  All four describe the same
``wide`` summary; format choice is a downstream-tooling preference.

LaTeX output is paper-ready: uses ``booktabs`` (\\toprule, \\midrule,
\\bottomrule), bolds Pareto-optimal cells, and escapes characters that
LaTeX's tabular cells cannot accept literally.

Output paths land under ``{output_dir}/tables/{output_prefix}_summary.{ext}``
(per the v0.6c-B layout).
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict

import pandas as pd


_BOLD_OPEN = "\\textbf{"
_BOLD_CLOSE = "}"


def _escape_latex(s: str) -> str:
    """Escape characters LaTeX's tabular doesn't accept literally.

    ``±`` → ``$\\pm$`` (cell context expects math mode for \\pm).
    Underscores, ampersands, %, # → backslash-prefixed.  Backslashes
    in already-escaped values (e.g., from a previous pass) are left
    alone — we only run this on plain numeric cells.
    """
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("±", "$\\pm$")
        .replace("_", "\\_")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("#", "\\#")
    )


def _is_pareto_cell(
    pareto_df: pd.DataFrame, family: str, baseline: str, n_nodes: int,
) -> bool:
    """Look up whether a (family, baseline, n_nodes) cell is Pareto-
    optimal.  Returns False on missing rows (defensive)."""
    rows = pareto_df[
        (pareto_df["family"] == family)
        & (pareto_df["baseline"] == baseline)
        & (pareto_df["n_nodes"] == n_nodes)
    ]
    if rows.empty:
        return False
    return bool(rows.iloc[0]["is_pareto"])


def write_csv(wide: pd.DataFrame, path: str | Path) -> None:
    """Standard CSV with ``na_rep='n/a'`` (the wide DataFrame already
    embeds explicit n/a strings; this guards against any residual
    NaN that slips through)."""
    wide.to_csv(path, na_rep="n/a")


def _df_to_markdown(df: pd.DataFrame) -> str:
    """Hand-rolled markdown renderer (avoids the optional ``tabulate``
    dependency).  Renders ``df`` with its index name as the leftmost
    column and column labels as the headers.

    Output is a github-flavoured-markdown table:

        | n_nodes | nbn-cat-ve | pgmpy-mle-ve |
        | --- | --- | --- |
        | 5 | 0.0429 | 0.0501 |
    """
    cols = [str(df.index.name or "index")] + [str(c) for c in df.columns]
    header = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join("---" for _ in cols) + " |"
    rows = [header, sep]
    for idx, row in df.iterrows():
        cells = [str(idx)] + [str(v) for v in row.tolist()]
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join(rows)


def write_markdown(wide: pd.DataFrame, path: str | Path) -> None:
    """Pretty markdown: one table per (family, metric) combination.

    Renders the wide DataFrame as a sequence of small markdown tables
    with H2 headers.  Suitable for embedding in README or for quick
    eyeballing.
    """
    lines: list[str] = []
    metric_descriptions = {
        "accuracy": "(W₁ for continuous / TV for discrete, lower is better)",
        "tv_per_node": "(per-node total variation, lower is better)",
        "jsd_per_node": "(per-node Jensen-Shannon divergence / log 2, lower is better)",
        "w1_per_node": "(per-node Wasserstein-1, lower is better)",
        "total_time_s": "(wall-clock query battery time, seconds)",
        "cpd_accuracy": "(per-CPD accuracy)",
    }
    for (family, metric), block in wide.groupby(level=["family", "metric"]):
        desc = metric_descriptions.get(metric, "")
        title = f"{family} — {metric} {desc}".rstrip()
        lines.append(f"## {title}")
        lines.append("")
        sub = block.copy()
        sub.index = sub.index.droplevel(["family", "metric"])
        sub.index.name = "n_nodes"
        lines.append(_df_to_markdown(sub))
        lines.append("")
    Path(path).write_text("\n".join(lines))


def write_latex(
    wide: pd.DataFrame, path: str | Path,
    pareto_df: pd.DataFrame | None = None,
) -> None:
    """Paper-ready LaTeX tables.  One ``\\begin{table}`` per (family,
    metric) pair, with ``\\toprule \\midrule \\bottomrule`` (booktabs).

    Pareto-optimal cells are wrapped in ``\\textbf{...}`` when the
    aggregator's ``pareto`` DataFrame is supplied.
    """
    lines: list[str] = [
        "% Generated by benchmarking._tables.write_latex.",
        "% Requires \\usepackage{booktabs} in the preamble.",
        "",
    ]
    for (family, metric), block in wide.groupby(level=["family", "metric"]):
        sub = block.copy()
        sub.index = sub.index.droplevel(["family", "metric"])
        n_nodes_list = list(sub.index)
        baselines = list(sub.columns)

        col_spec = "l" + "c" * len(n_nodes_list)
        caption = (
            f"{family.replace('_', ' ')} — {metric.replace('_', ' ')} "
            f"per baseline."
        )
        label = f"tab:{family}_{metric}"
        lines.append("\\begin{table}[h]")
        lines.append("\\centering")
        lines.append(f"\\caption{{{_escape_latex(caption)}}}")
        lines.append(f"\\label{{{label}}}")
        lines.append(f"\\begin{{tabular}}{{{col_spec}}}")
        lines.append("\\toprule")
        header = " & ".join(
            ["baseline"] + [f"$n={n}$" for n in n_nodes_list]
        ) + " \\\\"
        lines.append(header)
        lines.append("\\midrule")
        for baseline in baselines:
            row = [_escape_latex(baseline)]
            for n in n_nodes_list:
                cell = str(sub.loc[n, baseline])
                escaped = _escape_latex(cell)
                # Bold Pareto-optimal cells (only when the value is
                # numeric, not "n/a").
                if (
                    pareto_df is not None
                    and not cell.startswith("n/a")
                    and _is_pareto_cell(pareto_df, family, baseline, int(n))
                ):
                    escaped = f"{_BOLD_OPEN}{escaped}{_BOLD_CLOSE}"
                row.append(escaped)
            lines.append(" & ".join(row) + " \\\\")
        lines.append("\\bottomrule")
        lines.append("\\end{tabular}")
        lines.append("\\end{table}")
        lines.append("")
    Path(path).write_text("\n".join(lines))


def write_parquet(wide: pd.DataFrame, path: str | Path) -> None:
    """Parquet snapshot of the wide DataFrame for downstream tooling."""
    # The wide DataFrame has a MultiIndex; reset for a clean parquet
    # schema (all columns flat strings/values).
    wide.reset_index().to_parquet(path)


def write_all(
    aggregated: Dict[str, pd.DataFrame],
    output_dir: str | Path,
    output_prefix: str,
) -> Dict[str, Path]:
    """Convenience: write all four formats with the canonical naming
    ``{output_dir}/tables/{output_prefix}_summary.{ext}``.

    Returns a dict ``{format: written_path}``.
    """
    base = Path(output_dir) / "tables"
    base.mkdir(parents=True, exist_ok=True)
    paths = {
        "csv": base / f"{output_prefix}_summary.csv",
        "md": base / f"{output_prefix}_summary.md",
        "tex": base / f"{output_prefix}_summary.tex",
        "parquet": base / f"{output_prefix}_summary.parquet",
    }
    write_csv(aggregated["wide"], paths["csv"])
    write_markdown(aggregated["wide"], paths["md"])
    write_latex(
        aggregated["wide"], paths["tex"],
        pareto_df=aggregated.get("pareto"),
    )
    write_parquet(aggregated["wide"], paths["parquet"])
    return paths


__all__ = [
    "write_csv", "write_markdown", "write_latex", "write_parquet",
    "write_all", "_escape_latex",
]
